export enum UfEnum {
	AC = 'AC',
	AL = 'AL',
	AP = 'AP',
	AM = 'AM',
	BA = 'BA',
	CE = 'CE',
	DF = 'DF',
	ES = 'ES',
	GO = 'GO',
	MA = 'MA',
	MT = 'MT',
	MS = 'MS',
	MG = 'MG',
	PA = 'PA',
	PB = 'PB',
	PR = 'PR',
	PE = 'PE',
	PI = 'PI',
	RJ = 'RJ',
	RN = 'RN',
	RS = 'RS',
	RO = 'RO',
	RR = 'RR',
	SC = 'SC',
	SP = 'SP',
	SE = 'SE',
	TO = 'TO',
}

export const UfEnumMsg = {
  [UfEnum.AC]: 'Acre',
  [UfEnum.AL]: 'Alagoas',
  [UfEnum.AP]: 'Amapá',
  [UfEnum.AM]: 'Amazonas',
  [UfEnum.BA]: 'Bahia',
  [UfEnum.CE]: 'Ceará',
  [UfEnum.DF]: 'Distrito Federal',
  [UfEnum.ES]: 'Espirito Santo',
  [UfEnum.GO]: 'Goiás',
  [UfEnum.MA]: 'Maranhão',
  [UfEnum.MT]: 'Mato Grosso',
  [UfEnum.MS]: 'Mato Grosso do Sul',
  [UfEnum.MG]: 'Minas Gerais',
  [UfEnum.PA]: 'Pará',
  [UfEnum.PB]: 'Paraíba',
  [UfEnum.PR]: 'Paraná',
  [UfEnum.PE]: 'Pernambuco',
  [UfEnum.PI]: 'Piauí',
  [UfEnum.RJ]: 'Rio de Janeiro',
  [UfEnum.RN]: 'Rio Grande do Norte',
  [UfEnum.RS]: 'Rio Grande do Sul',
  [UfEnum.RO]: 'Rondônia',
  [UfEnum.RR]: 'Roraima',
  [UfEnum.SC]: 'Santa Catarina',
  [UfEnum.SP]: 'São Paulo',
  [UfEnum.SE]: 'Sergipe',
  [UfEnum.TO]: 'Tocantins',
};
